DiceWeb/DiceMVC/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DiceMVC.Models
{
    public class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        //public int Score { get; set; }

        public Dictionary<string, int> Values { get; set; }
        public Dictionary<string, bool> FreeValues { get; set; }
    }
}

DiceWeb/DiceMVC/Controllers/PlayerController.cs
using DiceMVC.Application.Interfaces;
using DiceMVC.Application.ViewModels.Player;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DiceMVC.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IPlayerService _playerService;
        private readonly IGameService _gameService;
        public PlayerController(IPlayerService playerService, IGameService gameService)
        {
            _playerService = playerService;
            _gameService = gameService;
        }
        [HttpGet]
        public IActionResult AddNewPlayer(int idGame)
        {
            return View(new NewPlayerVm(idGame));               //http with choice new or saved player
        }
        [HttpPost]
        public IActionResult AddNewPlayer(NewPlayerVm model)
        {
            var id = _playerService.AddNewPlayer(model);                                        //add new player, create approprate items in data base and get id of the game

            if (model.PlayerCount > model.PlayerNo + 1)                                         //check if player number is lower than count of player (players numbers start from 0 so it is increased by 1)...
                return RedirectToAction("NewOrLoadPlayer", new {idGame = model.GameId });       //...if player number is lower than html with choice new or saved player
            else                                                                                //...if player number is equal number of players
            {   _gameService.EndingCreate(model.GameId);                                        //create approprate items in data base and set approprate values
                return RedirectToAction("GamePlay", "Game", new { idGame = model.GameId });     //http with the game
            }
        }
        [HttpGet]
        public IActionResult NewOrLoadPlayer(int idGame)
        {
            return View(new NewOrLoadPlayerVm(idGame));                 //http with choice new or saved player
        }
        [HttpPost]
        public IActionResult NewOrLoadPlayer(NewOrLoadPlayerVm model)
        {
            var choose = model.CreateNewPlayer;                                         //set player's choice as "choose"
            var idGame = model.IdGame;                                                  //get the id of the game
            switch (choose)                                                             //check the player's choice...
            {
                case "New":                                                             //...if player's choice is "New"...
                    return RedirectToAction("AddNewPlayer", new { idGame = idGame });   //...http with creating new player
                    break;
                case "Load":                                                            //...if player's choic is "Load"...
                    return RedirectToAction("LoadPlayer", new { gameId = idGame });     ///...http with loading player
                    break;
                default:
                    return RedirectToAction("");
            }            
        }
        [HttpGet]
        public IActionResult LoadPlayer(int gameId)
        {
            var model = _playerService.GetPlayersForList();         //get all players to list
            model.GameId = gameId;                                  //set GameId as id of the game
            return View(model);                                     //http with loading player
        }
        [HttpPost]
        public IActionResult LoadPlayer(ListOfPlayersVm model)
        {
            var choosenPlayer = model.ChoosePlayer;                                         //set "choosenPlayer" as the player's choice
            model = _playerService.AddPlayerToGame(model);                                  //add chosen player to the game
            if (model.Count > model.PlayerNo)                                               //check if player number is lower than count of player...
                return RedirectToAction("NewOrLoadPlayer", new { idGame = model.GameId });  //...if player number is lower than html with choice new or saved player
            else                                                                            //...if player number is equal number of players
            {
                _gameService.EndingCreate(model.GameId);                                    //create approprate items in data base and set approprate values
                return RedirectToAction("GamePlay", "Game", new { gameId = model.GameId }); //http with the game
            }
        }
    }
}

DiceWeb/DiceMVC/Views/Player/AddNewPlayer.cshtml
@model DiceMVC.Application.ViewModels.Player.NewPlayerVm

@{
    ViewData["Title"] = "AddNewPlayer";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddNewPlayer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
                <input type="hidden" asp-for="Id" class="form-control" />
                <input type="hidden" asp-for="GameId" class="form-control"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DiceWeb/DiceMVC/Views/Player/AddPlayer.cshtml
@model DiceMVC.Application.ViewModels.Player.NewPlayerVm

@{
    ViewData["Title"] = "AddPlayer";
}

<h1>AddPlayer</h1>

<h4>NewPlayerVm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPlayer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
                <input type="hidden" asp-for="Id" class="form-control" />
                
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DiceWeb/DiceMVC/Views/Player/LoadPlayer.cshtml
@model DiceMVC.Application.ViewModels.Player.ListOfPlayersVm

@{
    ViewData["Title"] = "LoadPlayer";
}

<h4>Wybierz gracza</h4>

<div>
    <form asp-action="LoadPlayer" asp-controller="Player" method="post">
        <input type="hidden" asp-for="GameId"  value="@Model.GameId" />
        <input type="hidden" asp-for="PlayerNo"  />
        <table>

            <tbody>
                @foreach (var item in Model.Players)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            <div>
                                <label>
                                    <input type="radio" value="@item.Id" asp-for="ChoosePlayer" /><br />
                                </label>
                            </div>

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>

                    </tr>
                }
            </tbody>
        </table>
        <div>
            <input type="submit" value="Dalej" />
        </div>
    </form>

</div>

DiceWeb/DiceMVC/Views/Player/NewOrLoadPlayer.cshtml
@model DiceMVC.Application.ViewModels.Player.NewOrLoadPlayerVm

@{
    ViewData["Title"] = "NewOrLoadPlayer";
}

<div>
    <div>
        <form asp-action="NewOrLoadPlayer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <input type="hidden" asp-for="IdGame" class="form-control" />
            </div>
            <div>
                <input type="hidden" asp-for="TurnNo" class="form-control" />
            </div>
            <div>
                <label>
                    <input type="radio" class="form-check-input" value = "New" asp-for="CreateNewPlayer" /> Nowy Gracz<br />
                    <input type="radio" class="form-check-input" value= "Load" asp-for="CreateNewPlayer" /> Wczytaj Gracza
                </label>
            </div>
            <div>
                <input type="submit" value="Dalej" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>